return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "lua-language-server",
      "stylua",
      "html-lsp",
      "css-lsp",
      "prettier",
      "ts_ls",
      "intelephense",
      "clangd",
      "dockerls",
      "jsonls",
      "marksman",
      "pyright",
      "black",
      "isort",
      "tailwindcss-language-server",
      "taplo",
      "bash-language-server",
      "shellcheck",
      "shfmt",
      "gopls",
      "gofumpt",
      "goimports",
      "eslint_d",
      "phpstan",
    },
  },
}
