return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	opts = {
		ensure_installed = {
			"vim",
			"lua",
			"vimdoc",
			"html",
			"css",
			"javascript",
			"typescript",
			"tsx",
			"php",
			"sql",
			"json",
			"markdown",
			"markdown_inline",
			"c",
			"cpp",
			"dockerfile",
			"jsonc",
			"python",
			"toml",
		},
		sync_install = true,
		auto_install = false,
		highlight = {
			enable = true,
			use_languagetree = true,
			additional_vim_regex_highlighting = false,
		},
		indent = { enable = true },
	},
}
